GET http://localhost:3000/

### employees

GET http://localhost:3000/employees

### employees by role

GET http://localhost:3000/employees?role=INTERN

### employees by id

GET http://localhost:3000/employees/6

### Create user

POST http://localhost:3000/employees
content-type: application/json

{
    "name":"Christian Mayer",
    "email":"testing@testing.com",
    "role":"ADMIN"
}
### Update user

PATCH  http://localhost:3000/employees/
content-type: application/json

{
    "name":"Christian Mayer",
    "email":"testing@testing.com",
    "role":"ADMIN"
}

### Delete user

DELETE   http://localhost:3000/employees/2

