GET http://localhost:3000/

### employees

GET http://localhost:3000/api/employees

### employees by role

GET http://localhost:3000/employees?role=INTERN

### employees by id

GET http://localhost:3000/api/employees/1

### Create user

POST http://localhost:3000/employees
content-type: application/json

{
    "name":"Loree Mayer",
    "email":"testingl@testing.com",
    "role":"INTERN"
}
### Update user

PATCH  http://localhost:3000/employees/2
content-type: application/json

{
    "name":"Loree Mayer",
    "email":"testingl@testing.com",
    "role":"ADMIN"
}

### Delete user

DELETE   http://localhost:3000/employees/2

