GET http://localhost:3000/

### users

GET http://localhost:3000/users

### users by role

GET http://localhost:3000/users?role=INTERN

### users by id

GET http://localhost:3000/users/6

### Create user

POST http://localhost:3000/users
content-type: application/json

{
    "name":"Christian"
}
### Update user

PATCH  http://localhost:3000/users/
content-type: application/json

{
    "name":"Christian Mayer"
}

### Delete user

DELETE   http://localhost:3000/users/2

